name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/balbam-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: balbambalbam-ai-server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        working-directory: balbambalbam-ai-server
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest Docker image
        run: docker pull ${{ env.DOCKER_IMAGE }}

      - name: Stop existing container
        run: docker stop github-actions-demo || true

      - name: Remove existing container
        run: docker rm github-actions-demo || true

      - name: Run new container
        run: |
          docker run --name github-actions-demo \
            --rm -d -p 8000:8000 \
            ${{ env.DOCKER_IMAGE }}
